# -*- coding: utf-8 -*-
"""End-to - End customer retail project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ftQgvFUq9XxWBqJ6NRdet5Cf8ryZayqk
"""

import pandas as pd
import seaborn as sns
import matplotlib as plt

df = pd.read_csv('/content/customer_shopping_behavior.csv')

df.shape

df.describe()

df.info()

df.duplicated().sum()

df.isnull().sum()

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

df.isnull().sum()

# Remove spacing and into lower case
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df.columns

# feature engineering for new use ful column

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}
 # new column name
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

# show new columns
df[['frequency_of_purchases', 'purchase_frequency_days']].head(10)

# data bining

labels = ['Young Adult', 'Adult', 'Middle-age', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

df[['age', 'age_group']].head(10)

# delete 1 column from dataset
df.drop('promo_code_used', axis=1, inplace=True)
print(df.columns)

from google.colab import files

# 1. Save the DataFrame to a CSV file first
df.to_csv('cleaned_shopping_data.csv', index=False)

# 2. Download the created file
files.download('cleaned_shopping_data.csv')

df.shape